client_name: "St Antony's Embroidery Works"
client_address: "Marete Tower,\r\nKarukachal - Changanacherry Rd, \r\nAramanapady, Changanassery,\r\nKerala 686101"
client_contact: '09656884371'
client_gst: GSKER234YZ1235B2
tax_percentage: '18'
client_logo:
  - '32'
client_banking: "Bank Name: HDFC Bank\r\nAccount Number: 50200086169366\r\nIFSC Code: HDFC0004896\r\nBranch Name: FASHION DISTRICT"
client_email: premshankar.p.b@gmail.com
