_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en
uuid: 95eca623-ac99-437e-9d28-8e53d5270401
name: Stitchlyn
mail: support@stitchlyn.com
slogan: 'Customized ERP system'
page:
  403: ''
  404: ''
  front: /node/8
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
